# Generated by Django 5.0.9 on 2024-09-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_subscription_options_subscription_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={'ordering': ['subscription__order', 'order', 'featured', '-updated']},
        ),
        migrations.RenameField(
            model_name='subscriptionprice',
            old_name='Subscription',
            new_name='subscription',
        ),
    ]
